
import java.io.File;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sirat
 */
public class SearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchFrame
     */
    int selectedOrNot;
    String location;

    public SearchFrame() {
        initComponents();
        setLocationRelativeTo(null);
        desktopRadioButton.setActionCommand("desktop");
        dDriveRadioButton.setActionCommand("d");
        eDriveRadioButton.setActionCommand("e");
        customRadioButton.setActionCommand("custom");
        selectedOrNot = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        desktopRadioButton = new javax.swing.JRadioButton();
        dDriveRadioButton = new javax.swing.JRadioButton();
        eDriveRadioButton = new javax.swing.JRadioButton();
        customRadioButton = new javax.swing.JRadioButton();
        titleLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        locationTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputField = new javax.swing.JTextArea();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Bar");
        setMinimumSize(new java.awt.Dimension(544, 393));
        setPreferredSize(new java.awt.Dimension(550, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 400));
        getContentPane().setLayout(null);

        desktopRadioButton.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup.add(desktopRadioButton);
        desktopRadioButton.setText("Desktop");
        getContentPane().add(desktopRadioButton);
        desktopRadioButton.setBounds(76, 72, 120, 23);

        dDriveRadioButton.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup.add(dDriveRadioButton);
        dDriveRadioButton.setText("D: Drive");
        getContentPane().add(dDriveRadioButton);
        dDriveRadioButton.setBounds(76, 95, 110, 23);

        eDriveRadioButton.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup.add(eDriveRadioButton);
        eDriveRadioButton.setText("E: Drive");
        getContentPane().add(eDriveRadioButton);
        eDriveRadioButton.setBounds(76, 118, 100, 23);

        customRadioButton.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup.add(customRadioButton);
        customRadioButton.setText("Custom Location :");
        customRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(customRadioButton);
        customRadioButton.setBounds(76, 142, 130, 23);

        titleLabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        titleLabel.setText("Search Location :");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(76, 0, 290, 70);
        getContentPane().add(searchField);
        searchField.setBounds(60, 183, 330, 37);

        searchButton.setBackground(new java.awt.Color(255, 255, 0));
        searchButton.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 0, 0));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton);
        searchButton.setBounds(400, 178, 100, 47);

        locationTextField.setText("Location");
        getContentPane().add(locationTextField);
        locationTextField.setBounds(208, 133, 250, 30);

        outputField.setColumns(20);
        outputField.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        outputField.setForeground(new java.awt.Color(51, 0, 102));
        outputField.setRows(5);
        jScrollPane1.setViewportView(outputField);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 231, 398, 110);

        backGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\uk\\Documents\\NetBeansProjects\\Search Bar\\img\\back.jpg")); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(-50, -20, 626, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        if (desktopRadioButton.isSelected() || dDriveRadioButton.isSelected() || eDriveRadioButton.isSelected() || customRadioButton.isSelected()) {
            String s = buttonGroup.getSelection().getActionCommand();
            location = "";

            if (s.equals("desktop")) {
                location = "C:/Users/uk/Desktop";
                selectedOrNot = 1;
                //System.out.println("Desktop");
            } else if (s.equals("d")) {
                location = "D:";
                selectedOrNot = 1;
            } else if (s.equals("e")) {
                location = "E:";
                selectedOrNot = 1;
            } else if (s.equals("custom")) {
                location = locationTextField.getText();
                selectedOrNot = 1;
            }

//I Got Location
            try {
                outputField.setText("Search Result : \n....................\n");
                File dir = new File(location);
                for (File f : dir.listFiles()) {

                    if (f.getName().toLowerCase().contains(searchField.getText().toLowerCase())) {
                        // System.out.println(f.getName());
                        outputField.append("     "+f.getName() + "\n");
                    }

                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Location or Something Error...");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a Directory...");
        }


    }//GEN-LAST:event_searchButtonActionPerformed

    private void customRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton customRadioButton;
    private javax.swing.JRadioButton dDriveRadioButton;
    private javax.swing.JRadioButton desktopRadioButton;
    private javax.swing.JRadioButton eDriveRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JTextArea outputField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
